// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DemoProtocol.proto

package com.moon.protobufdemo.protobuf;

public final class DemoProtocol {
  private DemoProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DemoRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.moon.protobufdemo.protobuf.DemoRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string requestMsg = 1;</code>
     */
    boolean hasRequestMsg();
    /**
     * <code>optional string requestMsg = 1;</code>
     */
    java.lang.String getRequestMsg();
    /**
     * <code>optional string requestMsg = 1;</code>
     */
    com.google.protobuf.ByteString
        getRequestMsgBytes();
  }
  /**
   * Protobuf type {@code com.moon.protobufdemo.protobuf.DemoRequest}
   */
  public  static final class DemoRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.moon.protobufdemo.protobuf.DemoRequest)
      DemoRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DemoRequest.newBuilder() to construct.
    private DemoRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DemoRequest() {
      requestMsg_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DemoRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              requestMsg_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.moon.protobufdemo.protobuf.DemoProtocol.internal_static_com_moon_protobufdemo_protobuf_DemoRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.moon.protobufdemo.protobuf.DemoProtocol.internal_static_com_moon_protobufdemo_protobuf_DemoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest.class, com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest.Builder.class);
    }

    private int bitField0_;
    public static final int REQUESTMSG_FIELD_NUMBER = 1;
    private volatile java.lang.Object requestMsg_;
    /**
     * <code>optional string requestMsg = 1;</code>
     */
    public boolean hasRequestMsg() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional string requestMsg = 1;</code>
     */
    public java.lang.String getRequestMsg() {
      java.lang.Object ref = requestMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          requestMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string requestMsg = 1;</code>
     */
    @Override
    public com.google.protobuf.ByteString
        getRequestMsgBytes() {
      java.lang.Object ref = requestMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, requestMsg_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, requestMsg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest)) {
        return super.equals(obj);
      }
      com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest other = (com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest) obj;

      if (hasRequestMsg() != other.hasRequestMsg()) return false;
      if (hasRequestMsg()) {
        if (!getRequestMsg()
            .equals(other.getRequestMsg())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRequestMsg()) {
        hash = (37 * hash) + REQUESTMSG_FIELD_NUMBER;
        hash = (53 * hash) + getRequestMsg().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.moon.protobufdemo.protobuf.DemoRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.moon.protobufdemo.protobuf.DemoRequest)
        com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.moon.protobufdemo.protobuf.DemoProtocol.internal_static_com_moon_protobufdemo_protobuf_DemoRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.moon.protobufdemo.protobuf.DemoProtocol.internal_static_com_moon_protobufdemo_protobuf_DemoRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest.class, com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest.Builder.class);
      }

      // Construct using com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        requestMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.moon.protobufdemo.protobuf.DemoProtocol.internal_static_com_moon_protobufdemo_protobuf_DemoRequest_descriptor;
      }

      @java.lang.Override
      public com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest getDefaultInstanceForType() {
        return com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest build() {
        com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest buildPartial() {
        com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest result = new com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.requestMsg_ = requestMsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest) {
          return mergeFrom((com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest other) {
        if (other == com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest.getDefaultInstance()) return this;
        if (other.hasRequestMsg()) {
          bitField0_ |= 0x00000001;
          requestMsg_ = other.requestMsg_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object requestMsg_ = "";
      /**
       * <code>optional string requestMsg = 1;</code>
       */
      public boolean hasRequestMsg() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional string requestMsg = 1;</code>
       */
      public java.lang.String getRequestMsg() {
        java.lang.Object ref = requestMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            requestMsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string requestMsg = 1;</code>
       */
      public com.google.protobuf.ByteString
          getRequestMsgBytes() {
        java.lang.Object ref = requestMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string requestMsg = 1;</code>
       */
      public Builder setRequestMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        requestMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestMsg = 1;</code>
       */
      public Builder clearRequestMsg() {
        bitField0_ = (bitField0_ & ~0x00000001);
        requestMsg_ = getDefaultInstance().getRequestMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string requestMsg = 1;</code>
       */
      public Builder setRequestMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        requestMsg_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.moon.protobufdemo.protobuf.DemoRequest)
    }

    // @@protoc_insertion_point(class_scope:com.moon.protobufdemo.protobuf.DemoRequest)
    private static final com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest();
    }

    public static com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DemoRequest>
        PARSER = new com.google.protobuf.AbstractParser<DemoRequest>() {
      @java.lang.Override
      public DemoRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DemoRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DemoRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DemoRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.moon.protobufdemo.protobuf.DemoProtocol.DemoRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DemoResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.moon.protobufdemo.protobuf.DemoResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint32 ret = 1;</code>
     */
    boolean hasRet();
    /**
     * <code>optional uint32 ret = 1;</code>
     */
    int getRet();

    /**
     * <code>optional string responseMsg = 2;</code>
     */
    boolean hasResponseMsg();
    /**
     * <code>optional string responseMsg = 2;</code>
     */
    java.lang.String getResponseMsg();
    /**
     * <code>optional string responseMsg = 2;</code>
     */
    com.google.protobuf.ByteString
        getResponseMsgBytes();
  }
  /**
   * Protobuf type {@code com.moon.protobufdemo.protobuf.DemoResponse}
   */
  public  static final class DemoResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.moon.protobufdemo.protobuf.DemoResponse)
      DemoResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DemoResponse.newBuilder() to construct.
    private DemoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DemoResponse() {
      responseMsg_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DemoResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              ret_ = input.readUInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              responseMsg_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.moon.protobufdemo.protobuf.DemoProtocol.internal_static_com_moon_protobufdemo_protobuf_DemoResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.moon.protobufdemo.protobuf.DemoProtocol.internal_static_com_moon_protobufdemo_protobuf_DemoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse.class, com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse.Builder.class);
    }

    private int bitField0_;
    public static final int RET_FIELD_NUMBER = 1;
    private int ret_;
    /**
     * <code>optional uint32 ret = 1;</code>
     */
    public boolean hasRet() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional uint32 ret = 1;</code>
     */
    public int getRet() {
      return ret_;
    }

    public static final int RESPONSEMSG_FIELD_NUMBER = 2;
    private volatile java.lang.Object responseMsg_;
    /**
     * <code>optional string responseMsg = 2;</code>
     */
    public boolean hasResponseMsg() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional string responseMsg = 2;</code>
     */
    public java.lang.String getResponseMsg() {
      java.lang.Object ref = responseMsg_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          responseMsg_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string responseMsg = 2;</code>
     */
    public com.google.protobuf.ByteString
        getResponseMsgBytes() {
      java.lang.Object ref = responseMsg_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        responseMsg_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeUInt32(1, ret_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, responseMsg_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, ret_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, responseMsg_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse)) {
        return super.equals(obj);
      }
      com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse other = (com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse) obj;

      if (hasRet() != other.hasRet()) return false;
      if (hasRet()) {
        if (getRet()
            != other.getRet()) return false;
      }
      if (hasResponseMsg() != other.hasResponseMsg()) return false;
      if (hasResponseMsg()) {
        if (!getResponseMsg()
            .equals(other.getResponseMsg())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasRet()) {
        hash = (37 * hash) + RET_FIELD_NUMBER;
        hash = (53 * hash) + getRet();
      }
      if (hasResponseMsg()) {
        hash = (37 * hash) + RESPONSEMSG_FIELD_NUMBER;
        hash = (53 * hash) + getResponseMsg().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.moon.protobufdemo.protobuf.DemoResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.moon.protobufdemo.protobuf.DemoResponse)
        com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.moon.protobufdemo.protobuf.DemoProtocol.internal_static_com_moon_protobufdemo_protobuf_DemoResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.moon.protobufdemo.protobuf.DemoProtocol.internal_static_com_moon_protobufdemo_protobuf_DemoResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse.class, com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse.Builder.class);
      }

      // Construct using com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        ret_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        responseMsg_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.moon.protobufdemo.protobuf.DemoProtocol.internal_static_com_moon_protobufdemo_protobuf_DemoResponse_descriptor;
      }

      @java.lang.Override
      public com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse getDefaultInstanceForType() {
        return com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse.getDefaultInstance();
      }

      @java.lang.Override
      public com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse build() {
        com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse buildPartial() {
        com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse result = new com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.ret_ = ret_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.responseMsg_ = responseMsg_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse) {
          return mergeFrom((com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse other) {
        if (other == com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse.getDefaultInstance()) return this;
        if (other.hasRet()) {
          setRet(other.getRet());
        }
        if (other.hasResponseMsg()) {
          bitField0_ |= 0x00000002;
          responseMsg_ = other.responseMsg_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int ret_ ;
      /**
       * <code>optional uint32 ret = 1;</code>
       */
      public boolean hasRet() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>optional uint32 ret = 1;</code>
       */
      public int getRet() {
        return ret_;
      }
      /**
       * <code>optional uint32 ret = 1;</code>
       */
      public Builder setRet(int value) {
        bitField0_ |= 0x00000001;
        ret_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 ret = 1;</code>
       */
      public Builder clearRet() {
        bitField0_ = (bitField0_ & ~0x00000001);
        ret_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object responseMsg_ = "";
      /**
       * <code>optional string responseMsg = 2;</code>
       */
      public boolean hasResponseMsg() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>optional string responseMsg = 2;</code>
       */
      public java.lang.String getResponseMsg() {
        java.lang.Object ref = responseMsg_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            responseMsg_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string responseMsg = 2;</code>
       */
      public com.google.protobuf.ByteString
          getResponseMsgBytes() {
        java.lang.Object ref = responseMsg_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          responseMsg_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string responseMsg = 2;</code>
       */
      public Builder setResponseMsg(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        responseMsg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string responseMsg = 2;</code>
       */
      public Builder clearResponseMsg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        responseMsg_ = getDefaultInstance().getResponseMsg();
        onChanged();
        return this;
      }
      /**
       * <code>optional string responseMsg = 2;</code>
       */
      public Builder setResponseMsgBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        responseMsg_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.moon.protobufdemo.protobuf.DemoResponse)
    }

    // @@protoc_insertion_point(class_scope:com.moon.protobufdemo.protobuf.DemoResponse)
    private static final com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse();
    }

    public static com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<DemoResponse>
        PARSER = new com.google.protobuf.AbstractParser<DemoResponse>() {
      @java.lang.Override
      public DemoResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DemoResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DemoResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DemoResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.moon.protobufdemo.protobuf.DemoProtocol.DemoResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_moon_protobufdemo_protobuf_DemoRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_moon_protobufdemo_protobuf_DemoRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_moon_protobufdemo_protobuf_DemoResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_moon_protobufdemo_protobuf_DemoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022DemoProtocol.proto\022\036com.moon.protobufd" +
      "emo.protobuf\"!\n\013DemoRequest\022\022\n\nrequestMs" +
      "g\030\001 \001(\t\"0\n\014DemoResponse\022\013\n\003ret\030\001 \001(\r\022\023\n\013" +
      "responseMsg\030\002 \001(\tB\002H\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_moon_protobufdemo_protobuf_DemoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_moon_protobufdemo_protobuf_DemoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_moon_protobufdemo_protobuf_DemoRequest_descriptor,
        new java.lang.String[] { "RequestMsg", });
    internal_static_com_moon_protobufdemo_protobuf_DemoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_moon_protobufdemo_protobuf_DemoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_moon_protobufdemo_protobuf_DemoResponse_descriptor,
        new java.lang.String[] { "Ret", "ResponseMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
